blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/judeik/smarted-africa-app/wiki
    about: Check our project wiki for setup guides, usage, and developer docs
